language: java
jdk:
- oraclejdk8
install: true
script:
- gradle test
before_deploy:
- export TAGGED_VERSION="$BUILD_VERSION.$TRAVIS_BUILD_NUMBER"
- export WINDOWS_32_JRE="windows-x86-1.8.0_66.tar.gz"
- export WINDOWS_64_JRE="windows-amd64-1.8.0_66.tar.gz"
- export MAC_JRE="macosx-amd64-1.8.0_66.tar.gz"
- export ASSET_URL="http://github.com/triplea-game/assets/blob/master/install4j"
- export JRE_HOME="~isntall4j6/jres"

- echo "Downloading and installing install4j"
- wget -O install4j_unix.sh $ASSET_URL/install4j_unix_6_0_4.sh?raw=true
- chmod +x install4j_unix.sh
- ./install4j_unix.sh -q

- echo "Downloading JREs that will be bundled with installers"
- wget -O $MAC_JRE $ASSET_URL/$MAC_JRE?raw=true
- mv $MAC_JRE $JRE_HOME

- wget -O $WINDOWS_32_JRE_JRE $ASSET_URL/$WINDOWS_32_JRE_JRE?raw=true
- mv $WINDOWS_32_JRE_JRE $JRE_HOME

- wget -O $WINDOWS_64_JRE_JRE $ASSET_URL/$WINDOWS_64_JRE_JRE?raw=true
- mv $WINDOWS_64_JRE_JRE $JRE_HOME


- mkdir -p ~/.gradle
- grep -q "install4jHomeDir" ~/.gradle/gradle.properties 2> /dev/null || echo "install4jHomeDir=$(cd ~ && pwd)/install4j6" >> ~/.gradle/gradle.properties

- echo "Now Running Install4j to build OS specific installers"
- ~/install4j6/bin/install4jc -L $INSTALL4J_LICENSE

- echo "Now executing gradle to build the rest of the deployment artifacts, for lobby, bot servers, etc.."
- gradle release

- echo "Configure Git and PUSH A TAG - this trigger and execute the deploy section of this same build file, in the same travis linux container (skip_cleanup setting below is important)"
- git config --global user.email "tripleabuilderbot@gmail.com"
- git config --global user.name "tripleabuilderbot"
- git tag $TAGGED_VERSION -a -m "$TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-game/triplea --tags 2>&1 | sed 's|https://.*github|https://[secure]@github|'
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  ## This is the list of files to be deployed to github releases
  file:
    - build/libs/triplea-${TAGGED_VERSION}-all.jar
    - build/releases/triplea_windows_${TAGGED_VERSION}.exe
    - build/releases/triplea_macos_${TAGGED_VERSION}.dmg
    - build/releases/triplea_unix_${TAGGED_VERSION}.sh
    - build/distributions/triplea-${TAGGED_VERSION}-all_platforms.zip
    - build/distributions/triplea-${TAGGED_VERSION}-bots.zip
    - build/distributions/triplea-${TAGGED_VERSION}-server.zip
  skip_cleanup: true
  prerelease: true
  on:
    repo: triplea-game/triplea
    tags: false
    branches:
      only:
        - master
